In [9]:
import os
import cv2
import joblib
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, class_likelihood_ratios


In [10]:
dataset_path =R"C:\Users\ADMIN\Desktop\rice_ml\Rice_Image_Dataset"

In [11]:
images = []
labels = []
IMG_SIZE = 64
for folder in os.listdir(dataset_path):
    folder_path = os.path.join(dataset_path,folder)
    if os.path.isdir(folder_path):
        for image_name in os.listdir(folder_path):
            image_path = os.path.join(folder_path,image_name)

            image = cv2.imread(image_path)
            if image is None:
                continue
            image = cv2.resize(image,(IMG_SIZE,IMG_SIZE))
            image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)

            feature = image.flatten()

            images.append(feature)
            labels.append(folder)

# print(labels)
print("Number of images:", len(images))
print("Number of labels:", len(labels))
print("Classes:", set(labels))

Number of images: 75000
Number of labels: 75000
Classes: {'Arborio', 'Karacadag', 'Jasmine', 'Basmati', 'Ipsala'}


In [12]:
X = np.array(images)
y = np.array(labels)

print("images : ",X.shape)
print("labes : ",y.shape)

encoder = LabelEncoder()
y = encoder.fit_transform(y)

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


model = RandomForestClassifier(random_state=42,n_estimators=100)

model.fit(X_train,y_train)

y_predict = model.predict(X_test)

print("accuracy_score : ",accuracy_score(y_test,y_predict))
print("."*60)
print("classification_report  : ",classification_report(y_test,y_predict))
print("."*60)
print("confusion_matrix : ",confusion_matrix(y_test,y_predict))
print("."*60)

joblib.dump(model,"rice_ml_model.pkl")
joblib.dump(model,"label_encoder.pkl")


print("model saved succussfully......")

images :  (75000, 12288)
labes :  (75000,)
accuracy_score :  0.9934666666666667
............................................................
classification_report  :                precision    recall  f1-score   support

           0       0.99      0.99      0.99      2997
           1       1.00      0.99      0.99      2995
           2       1.00      1.00      1.00      3083
           3       0.99      1.00      0.99      2996
           4       1.00      0.99      0.99      2929

    accuracy                           0.99     15000
   macro avg       0.99      0.99      0.99     15000
weighted avg       0.99      0.99      0.99     15000

............................................................
confusion_matrix :  [[2971    0    0   17    9]
 [   0 2971    0   24    0]
 [   6    0 3075    2    0]
 [   0   12    0 2983    1]
 [  26    0    0    1 2902]]
............................................................
model saved succussfully......
